# Generated by Django 2.2.17 on 2021-01-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0033_taskassignee_board_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='current_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
